name: Run main.py

on:
  workflow_dispatch:  # Allows manual execution
  schedule:
    - cron: '0 * * * *'  # Runs every hour (change as needed)

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --force-reinstall numpy
          pip install -r requirements.txt || true
      - name: Run main.py (Keep it Running)
        run: |
          python main.py &  # Run in background
          sleep 21600  # Keep job running for 6 hours (21600 seconds)
